### ISSUE TITLE
Integrate plotly candlestick rendering

### ISSUE THREAD

**Issue by igorfialko** [alexarchambault/plotly-scala#173]
I'd like to integrate plotly's candlestick graph type like here:
https://plotly.com/javascript/candlestick-charts/
Could you provide some guidance on whether it's possible and how it's to be done.

**Comment by alexarchambault** [comment]
@igorfialko Kind of late answer here. There's already [some guidance in the README](https://github.com/alexarchambault/plotly-scala/blob/master/README.md#adding-support-for-extra-plotlyjs-features). That involves finding some plotly.js doc page you want to enable in [this directory](https://github.com/alexarchambault/plotly-documentation/tree/eae136bb920c7542654a5e13cff04a0de175a08d/_posts/plotly_js), enabling it in the plotly-scala tests, then adding the relevant definitions in plotly-scala until the added test pass.

**Comment by igorfialko** [comment]
@alexarchambault Thanks. I've already worked my way through the code. Couldn't find that part of the readme at the moment of writing the issue. I've integrated plotly's candlestick. Unfortunately it turns to be very slow due to plotly's way of rendering bars. But thats a bit off-topic. If you want I could create a pull request with candlestick?

**Comment by alexarchambault** [comment]
> If you want I could create a pull request with candlestick?

Go ahead!
