### ISSUE TITLE
upgrade circe

### ISSUE THREAD

**Issue by josefstr** [alexarchambault/plotly-scala#2]
Hi. Do you have plans to upgrade plotly-scala to circe 0.6.0, so that also a newer cats version  is used? A quick look into it showed me that main part would be to replace cats.data.Xor with cats.dataEitherT

**Comment by alexarchambault** [comment]
Sorry I forgot about this issue, I switched to circe 0.6 anyway in the mean time.

**Comment by josefstr** [comment]
No problem I forked plotly-scala and upgrade it here: https://github.com/josefstr/plotly-scala

btw. do you plan to upgrade to scalaVersion 2.12 ?

**Comment by alexarchambault** [comment]
Here you go: https://github.com/alexarchambault/plotly-scala/pull/6.
