### ISSUE TITLE
``Axis.automargin`` not there yet

### ISSUE THREAD

**Issue by schlichtanders** [alexarchambault/plotly-scala#42]
plotly has implemented a crucial automargin flag
https://plot.ly/javascript/setting-graph-size/#automatically-adjust-margins

which essentially fixed this issue with axislabels overlapping long axisticklabels
https://github.com/plotly/plotly.js/issues/1504

would be great if it could be supported

**Comment by sbrunk** [comment]
@schlichtanders this as well as #41 should work as soon as @alexarchambault cuts a new release.

See https://nbviewer.jupyter.org/github/sbrunk/almond-examples/blob/plotly-automargin/plotly_automargin.ipynb for an example.
