### ISSUE TITLE
Argonaut dependency issue

### ISSUE THREAD

**Issue by kyprifog** [alexarchambault/plotly-scala#86]
Following the basic tutorials I got, for almond in a jupyter notebook:

java.lang.NoSuchMethodError: argonaut.Argonaut$.ToJsonIdentity(Ljava/lang/Object;)Largonaut/JsonIdentity;

Tried importing argonaut directly but didnt work.

**Comment by sbrunk** [comment]
That looks like a version mismatch between almond and plotly-scala (the version in the README is not up to date at the moment). Which versions are you using? In general the latest published versions should be compatible.

```scala
import $ivy.`org.plotly-scala::plotly-almond:0.7.0`
```
should work for almond >= 0.4.0

**Comment by kyprifog** [comment]
Thank fixed it, thank you!

**Comment by trepidacious** [comment]
I still get this with the latest docker version of almond, and plotly-almond 0.7.0?

**Comment by trepidacious** [comment]
Apologies, I think I must have made a mistake, this now seems to work fine.
